@startuml

set namespaceSeparator none
left to right direction

skinparam BackgroundColor #FDFDFD
skinparam RoundCorner 8

skinparam class {
    BackgroundColor #EDF2F7
    BorderColor #A0AEC0
    FontColor #2D3748

    BackgroundColor<<MB>> #D1D9E6
    BorderColor<<MB>> #8A9AAB

    BackgroundColor<<SO>> #D2E4D8
    BorderColor<<SO>> #94B49F
}

hide empty members

!define MonoBehaviour(x) class x << (M,#8A9AAB) MB >>
!define ScriptableObject(x) class x << (S,#94B49F) SO >>
!define PrivateSerialized(x) - [<color:#00C732>S</color>] x
!define PublicSerialized(x) + [<color:#00C732>S</color>] x

MonoBehaviour(Billboard) {
}
MonoBehaviour(CandyTypeLookup) {
  + name : string
  + candyPrefab : GameObject
  + index : int
  + Get() : CandyTypeOption
}
class CandyTypeOption {
  + name : string
  + candyPrefab : GameObject
  + index : int
}
MonoBehaviour(PlayerDeck) {
  + chance : float
  + typeIndex : int
  + GetCandy() : void
  + AddToHand() : void
}
class DeckOption {
  + chance : float
  + typeIndex : int
  + GetCandy() : void
}
class CandyOption {
  + chance : float
  + typeIndex : int
}
MonoBehaviour(QuestSystem) {
  + pointRequirement : int
  + GetText() : string
}
class Quest {
  + pointRequirement : int
  + GetText() : string
}
MonoBehaviour(BoardItem) {
  + OnAddToHand : Action
  + OnInitiate : Action
  + OnAddToBoard : Action
  + Initiate() : void
}
MonoBehaviour(BoardItemComponent) {
  + ConnectToBoardItem() : virtual void
}
class GridMoveable {
  + ConnectToBoardItem() : override void
  + SetMoving() : void
  + SetTarget() : void
  + ResetTarget() : void
  + HasTarget() : bool
}
class GridRotatable {
  + ConnectToBoardItem() : override void
  + RotateClockWise() : void
}
class HandHandler {
  + OnHandGrabRelease : Action
  + ConnectToBoardItem() : override void
  + AddToHand() : void
  + OnGrabReleased() : static void
}
MonoBehaviour(Interactable) {
  + boardItem : BoardItem
  + Trigger() : void
  + HasBoardItemParent() : bool
}
class MoveToGridPosition {
}
class CandyActor {
  + candyType : int
  + OnGrabReleased() : static void
}
class CandyGroupHandle {
  + OnEnableObject() : void
  + OnDisableObject() : void
  + SetParent() : void
}
class CandyHandle {
  + rb : readonly Rigidbody
  + actor : readonly CandyActor
  + gameObject : readonly GameObject
}
MonoBehaviour(GridGenerator) {
  + cellSize : Vector2
  + Width : int
  + Height : int
  + GetAllPositions() : List<Vector3?>
  + GetAllOffGridPositions() : List<Vector3?>
  + GetPosAt() : Vector3
  + GetOffGridPosAt() : Vector3
}
MonoBehaviour(GridManager) {
  + position : Vector3
  + index : readonly int
  + gameObj : readonly GameObject
  + offGrid : bool
  + GetNearestPosition() : GridInstance
  + GetNearestOffGridPosition() : GridInstance
  + GetNearestGridPosition() : GridInstance
  + ReleaseInstance() : void
  + ForAllGridItems() : void
}
class GridInstance {
  + position : Vector3
  + index : readonly int
  + gameObj : readonly GameObject
  + offGrid : bool
}
MonoBehaviour(TurnManager) {
  + NextTurn() : void
}
class ComponentRegistry {
  + ComponentType : string
  + toCall : Action
  + AddToRegistry() : static bool
  + RemoveFromRegistry() : static bool
  + ReplaceInRegistry() : static bool
}
class Subscriber {
  + ComponentType : string
  + toCall : Action
}
MonoBehaviour(DeviceTracker) {
}
MonoBehaviour(FPSCounter) {
}
interface IPoolable {
}
MonoBehaviour(ResolutionTracker) {
  + OnResolutionChanged : static Action<int, int>
}
class Timer {
  + UpdateTime() : void
  + Reset() : void
  + ResetAndReplay() : void
  + Stop() : void
  + Play() : void
  + AddToMaxTime() : void
  + RegisterOnEndListener() : void
  + UnregisterOnEndListener() : void
  + RegisterOnPlayingListener() : void
  + UnregisterOnPlayingListener() : void
  + GetSecondsInTimeFormatted() : static string
  + GetCurrentTimeFormatted() : string
}
class VectorExtensions {
  + XY() : static Vector2
  + OverwriteXY() : static Vector3
}
MonoBehaviour(InteractionHandler) {
  + IsHoldingInteractable() : bool
}
MonoBehaviour(ItemRotationHandler) {
}
MonoBehaviour(MovementHandler) {
  + Velocity : Vector2
  + MovementDirection : Vector2
  + ApplyMouseDelta() : void
  + SetTargetZ() : void
  + ResetToOriginalZ() : void
}
MonoBehaviour(PlayerHandManager) {
  + OnGrabReleased : Action<Vector2, Vector2>
  + SetStateToGrabbing() : void
}
MonoBehaviour(VisualHandler) {
  + key : string
  + visual : Sprite
  + z : float
  + SetSprite() : void
}
struct VisualState {
  + key : string
  + visual : Sprite
  + z : float
}

BoardItem <|-- CandyActor
BoardItem --> BoardItemComponent
BoardItem --> Interactable
BoardItemComponent <|-- GridMoveable
BoardItemComponent <|-- GridRotatable
BoardItemComponent <|-- HandHandler
BoardItemComponent --> BoardItem
CandyActor --> HandHandler
CandyActor --> MoveToGridPosition
CandyGroupHandle --> CandyActor
CandyGroupHandle --> CandyHandle
CandyGroupHandle --> PlayerHandManager
CandyHandle --> CandyActor
CandyTypeLookup --> CandyTypeOption
ComponentRegistry --> Subscriber
DeckOption --> CandyOption
DeckOption --> CandyTypeLookup
GridManager --> GridGenerator
GridManager --> GridInstance
GridMoveable <|-- MoveToGridPosition
GridMoveable --> GridManager
GridRotatable --> HandHandler
HandHandler --> PlayerHandManager
Interactable --> BoardItem
InteractionHandler --> Interactable
InteractionHandler --> MovementHandler
InteractionHandler --> VisualHandler
IPoolable <|.. CandyGroupHandle
ItemRotationHandler --> GridRotatable
ItemRotationHandler --> Interactable
ItemRotationHandler --> InteractionHandler
MoveToGridPosition --> Timer
PlayerDeck --> CandyGroupHandle
PlayerDeck --> CandyOption
PlayerDeck --> CandyTypeLookup
PlayerDeck --> DeckOption
PlayerDeck --> PlayerHandManager
PlayerHandManager --> DeviceTracker
PlayerHandManager --> InteractionHandler
PlayerHandManager --> ItemRotationHandler
PlayerHandManager --> MovementHandler
PlayerHandManager --> VisualHandler
QuestSystem --> Quest
TurnManager --> GridManager
TurnManager --> MoveToGridPosition
VisualHandler --> VisualState
@enduml
